version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6464:6464"
    # environment:
      # Add any environment variables here if needed
      # EXAMPLE_VAR: value
    volumes:
      - .:/opt/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "6464"]
